server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  data:
    mongodb:
      uri: mongodb://localhost:27017/power_school_gateway_dev
      database: power_school_gateway_dev
  liquibase:
    enabled: false
  cloud:
    gateway:
      routes:
        - id: USER-MICROSERVICE
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: RemoveRequestHeader
              args:
                name: Api-private-Key
            - name: AddRequestHeader
              args:
                name: X-Test-RequestHeader
                value: ApiGatewayRequest
            - name: AddResponseHeader
              args:
                name: X-Test-ResponseHeader
                value: ApiGatewayResponse
            - name: CircuitBreaker
              args:
                name: USER-MICROSERVICE-CB
                fallbackUri: forward:gateway/api/v1/user-fallback
            - name: CustomRoute
              args:
                country: India
            - name: Retry
              args:
                    retries: 3
                    methods: GET, DELETE
            - name: AuthenticationFilter
            - name: RateLimiterFilter
              args:
                strategy: TOKEN_BUCKET

resilience4j:
  circuitbreaker:
    instances:
      USER-MICROSERVICE-CB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  level:
    io:
      github:
        resilience4j:
          circuitbreaker: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
